[profile.default]
# solc = '0.8.14'
src = 'solidity'
test = 'solidity/test'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
optimizer_runs = 10_000

[fmt]
quote_style = 'single'
single_line_statement_blocks = 'single'

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000

[profile.test]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
src = 'solidity/test'

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
goerly = "${GOERLY_RPC}"

# for assemly msize instruction we disable yul
[profile.default.optimizer_details]
yul = false